<?php

return [
    'ventas-periodo' => [
        'id' => 'reports.ventas-periodo',
        'name' => 'Ventas por Período',
        'area' => 'Ventas',
        'description' => 'Ingresos totales, evolución diaria, comparativa con período anterior.',
        'route' => 'reportes.ventas.periodo',
        'icon' => 'chart-bar',
        'plan_feature' => 'report.ventas-periodo',
        'permission' => 'reports.ventas-periodo',
        'phase' => 1,
    ],
    'ventas-productos' => [
        'id' => 'reports.ventas-productos',
        'name' => 'Top Productos y Categorías',
        'area' => 'Ventas',
        'description' => 'Productos estrella, categorías que más venden, contribución al total.',
        'route' => 'reportes.ventas.productos',
        'icon' => 'cube',
        'plan_feature' => 'report.ventas-productos',
        'permission' => 'reports.ventas-productos',
        'phase' => 2,
    ],
    'ventas-pago' => [
        'id' => 'reports.ventas-pago',
        'name' => 'Ventas por Método de Pago',
        'area' => 'Ventas',
        'description' => 'Composición de cobros: efectivo, tarjeta, transferencia, mixto.',
        'route' => 'reportes.ventas.pago',
        'icon' => 'credit-card',
        'plan_feature' => 'report.ventas-pago',
        'permission' => 'reports.ventas-pago',
        'phase' => 2,
    ],
    'ventas-ticket' => [
        'id' => 'reports.ventas-ticket',
        'name' => 'Ticket Promedio y Devoluciones',
        'area' => 'Ventas',
        'description' => 'Valor promedio por venta, impacto de devoluciones y mermas.',
        'route' => 'reportes.ventas.ticket',
        'icon' => 'receipt',
        'plan_feature' => 'report.ventas-ticket',
        'permission' => 'reports.ventas-ticket',
        'phase' => 2,
    ],
    'taller-productividad' => [
        'id' => 'reports.taller-productividad',
        'name' => 'Productividad por Técnico',
        'area' => 'Taller',
        'description' => 'Rendimiento individual: OT completadas, tiempo promedio, carga activa.',
        'route' => 'reportes.taller.productividad',
        'icon' => 'users',
        'plan_feature' => 'report.taller-productividad',
        'permission' => 'reports.taller-productividad',
        'phase' => 1,
    ],
    'taller-ciclo-vida' => [
        'id' => 'reports.taller-ciclo-vida',
        'name' => 'Ciclo de Vida / Cuellos de Botella',
        'area' => 'Taller',
        'description' => 'Tiempo por estado, distribución del flujo, órdenes estancadas.',
        'route' => 'reportes.taller.ciclo-vida',
        'icon' => 'chart-bar',
        'plan_feature' => 'report.taller-ciclo-vida',
        'permission' => 'reports.taller-ciclo-vida',
        'phase' => 3,
    ],
    'taller-sla' => [
        'id' => 'reports.taller-sla',
        'name' => 'SLA / Órdenes Atrasadas',
        'area' => 'Taller',
        'description' => 'Cumplimiento de tiempos de entrega, OT en riesgo, edad de OT activas.',
        'route' => 'reportes.taller.sla',
        'icon' => 'clock',
        'plan_feature' => 'report.taller-sla',
        'permission' => 'reports.taller-sla',
        'phase' => 3,
    ],
    'taller-cotizaciones' => [
        'id' => 'reports.taller-cotizaciones',
        'name' => 'Conversión de Cotizaciones',
        'area' => 'Taller',
        'description' => 'Tasa de cierre: enviadas vs aprobadas, tiempo de respuesta, monto cotizado vs aprobado.',
        'route' => 'reportes.taller.cotizaciones',
        'icon' => 'trending-up',
        'plan_feature' => 'report.taller-cotizaciones',
        'permission' => 'reports.taller-cotizaciones',
        'phase' => 1,
    ],
    'taller-dispositivos' => [
        'id' => 'reports.taller-dispositivos',
        'name' => 'Dispositivos más Reparados',
        'area' => 'Taller',
        'description' => 'Top marcas y modelos, problemas frecuentes, ticket promedio por equipo.',
        'route' => 'reportes.taller.dispositivos',
        'icon' => 'device-phone-mobile',
        'plan_feature' => 'report.taller-dispositivos',
        'permission' => 'reports.taller-dispositivos',
        'phase' => 2,
    ],
    'inventario-valorizacion' => [
        'id' => 'reports.inventario-valorizacion',
        'name' => 'Valorización de Stock y Stock Crítico',
        'area' => 'Inventario',
        'description' => 'Valor total del inventario, productos bajo mínimo, reposición priorizada.',
        'route' => 'reportes.inventario.valorizacion',
        'icon' => 'archive-box',
        'plan_feature' => 'report.inventario-valorizacion',
        'permission' => 'reports.inventario-valorizacion',
        'phase' => 1,
    ],
    'inventario-rotacion' => [
        'id' => 'reports.inventario-rotacion',
        'name' => 'Rotación de Inventario y Obsoletos',
        'area' => 'Inventario',
        'description' => 'Velocidad de movimiento del inventario, productos sin ventas, capital inmovilizado.',
        'route' => 'reportes.inventario.rotacion',
        'icon' => 'arrows-arrow-right-left',
        'plan_feature' => 'report.inventario-rotacion',
        'permission' => 'reports.inventario-rotacion',
        'phase' => 3,
    ],
    'inventario-kardex' => [
        'id' => 'reports.inventario-kardex',
        'name' => 'Kardex Consolidado',
        'area' => 'Inventario',
        'description' => 'Movimientos de inventario: entradas, salidas, reservas, devoluciones, mermas.',
        'route' => 'reportes.inventario.kardex',
        'icon' => 'document-text',
        'plan_feature' => 'report.inventario-kardex',
        'permission' => 'reports.inventario-kardex',
        'phase' => 2,
    ],
    'caja-cuadre' => [
        'id' => 'reports.caja-cuadre',
        'name' => 'Cuadre de Caja por Turno',
        'area' => 'Caja',
        'description' => 'Verificación de efectivo por turno, descuadres, incidentes.',
        'route' => 'reportes.caja.cuadre',
        'icon' => 'banknotes',
        'plan_feature' => 'report.caja-cuadre',
        'permission' => 'reports.caja-cuadre',
        'phase' => 1,
    ],
    'caja-flujo' => [
        'id' => 'reports.caja-flujo',
        'name' => 'Flujo de Efectivo Diario',
        'area' => 'Caja',
        'description' => 'Entradas, salidas, devoluciones y saldo acumulado del día.',
        'route' => 'reportes.caja.flujo',
        'icon' => 'currency-dollar',
        'plan_feature' => 'report.caja-flujo',
        'permission' => 'reports.caja-flujo',
        'phase' => 2,
    ],
    'clientes-retencion' => [
        'id' => 'reports.clientes-retencion',
        'name' => 'Clientes Nuevos vs Recurrentes',
        'area' => 'Clientes',
        'description' => 'Retención de clientes, cohortes, clientes nuevos vs recurrentes.',
        'route' => 'reportes.clientes.retencion',
        'icon' => 'user-group',
        'plan_feature' => 'report.clientes-retencion',
        'permission' => 'reports.clientes-retencion',
        'phase' => 3,
    ],
    'clientes-top' => [
        'id' => 'reports.clientes-top',
        'name' => 'Top Clientes',
        'area' => 'Clientes',
        'description' => 'Clientes más valiosos por gasto y frecuencia, segmentación VIP.',
        'route' => 'reportes.clientes.top',
        'icon' => 'trophy',
        'plan_feature' => 'report.clientes-top',
        'permission' => 'reports.clientes-top',
        'phase' => 2,
    ],
    'cotizaciones-aprobacion' => [
        'id' => 'reports.cotizaciones-aprobacion',
        'name' => 'Tasa de Aprobación de Cotizaciones',
        'area' => 'Cotizaciones',
        'description' => 'Cotizaciones enviadas, aprobadas, rechazadas, tiempo de respuesta.',
        'route' => 'reportes.cotizaciones.aprobacion',
        'icon' => 'check-badge',
        'plan_feature' => 'report.cotizaciones-aprobacion',
        'permission' => 'reports.cotizaciones-aprobacion',
        'phase' => 1,
    ],
    'saas-mrr' => [
        'id' => 'reports.saas-mrr',
        'name' => 'MRR / ARR y Suscripciones',
        'area' => 'SuperAdmin',
        'description' => 'Ingresos recurrentes, suscripciones activas, distribución por plan.',
        'route' => 'reportes.saas.mrr',
        'icon' => 'chart-bar',
        'plan_feature' => 'report.saas-mrr',
        'permission' => 'reports.saas-mrr',
        'phase' => 4,
    ],
    'saas-crecimiento' => [
        'id' => 'reports.saas-crecimiento',
        'name' => 'Crecimiento, Churn y Tenants Activos',
        'area' => 'SuperAdmin',
        'description' => 'Adopción y abandono del SaaS: nuevos, cancelados, actividad real.',
        'route' => 'reportes.saas.crecimiento',
        'icon' => 'trending-up',
        'plan_feature' => 'report.saas-crecimiento',
        'permission' => 'reports.saas-crecimiento',
        'phase' => 4,
    ],
    'saas-uso' => [
        'id' => 'reports.saas-uso',
        'name' => 'Uso por Tenant',
        'area' => 'SuperAdmin',
        'description' => 'OT/ventas por tenant, usuarios activos, almacenamiento, límites del plan.',
        'route' => 'reportes.saas.uso',
        'icon' => 'building-storefront',
        'plan_feature' => 'report.saas-uso',
        'permission' => 'reports.saas-uso',
        'phase' => 4,
    ],
];
